"""added columns

Revision ID: c04be054e017
Revises: e5be9a909d84
Create Date: 2024-03-05 12:35:50.230727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04be054e017'
down_revision = 'e5be9a909d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
